name: Deploy to Production

on:
  push:
    branches:
      - server # 这里保持不变，当main分支有推送时，才触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: 'tux'
          port: 33448
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "正在连接到服务器..."
            cd /home/tux/ace-health
            echo "拉取最新代码..."
            git fetch --all
            # 将本地分支强制重置为远程的 'server' 分支
            git reset --hard origin/server
            echo "安装依赖..."
            bun install --frozen-lockfile
            echo "使用 PM2 重启服务..."
            pm2 reload ecosystem.config.cjs --env production
            echo "部署完成！"